version: '3.8'

services:
  minimal-dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: minimal-dashboard
    restart: always
    networks:
      - god-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.minimal-dashboard.rule=Host(`octademo.optoplus.ir`)"
      - "traefik.http.routers.minimal-dashboard.entrypoints=web"
      - "traefik.http.services.minimal-dashboard.loadbalancer.server.port=80"

networks:
  god-network:
    external: true
